[package]
name = "rust_lib_fdls"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.1.0"

anyhow    = "1.0.86"
once_cell = "1.19.0"
pipewire  = "0.8.0"
